#!/bin/bash


echo Content-type: text/html
echo
echo "<pre>"

# removing old files.
rm -f L.g
rm -f rt*
rm -f *.pix
rm -f temp*
rm -f ../../cgi-images/*

#initialising variable for the values filled in the form
x=`echo "$QUERY_STRING" | cut -d"&" -f1 | cut -d"=" -f2`
y=`echo "$QUERY_STRING" | cut -d"&" -f2 | cut -d"=" -f2`
#defining various views
front=frontview
side=sideview
top=topview
iso=isoview

cat <<EOF | env /usr/brlcad/dev-7.25.0/bin//mged -c L.g
in s1 rpp 0 1 0 $x 0 1
in s2 rpp 0 $y 0 1 0 1
r reg u s1 u s2  
mater reg plastic 164 222 0 0
B reg
ae 270 0
saveview $side
ae -90 90 
saveview $top
ae 225 45
saveview $iso
EOF

# adding "env /usr/brlcad/dev-7.25.0//bin/" in the beginning of 2nd line of raytracing file
# and sending output to temporary file.
sed '2cenv /usr/brlcad/dev-7.25.0//bin/rt -M \\' $front > tempFile1
sed '2cenv /usr/brlcad/dev-7.25.0//bin/rt -M \\' $side > tempFile2
sed '2cenv /usr/brlcad/dev-7.25.0//bin/rt -M \\' $top > tempFile3
sed '2cenv /usr/brlcad/dev-7.25.0//bin/rt -M \\' $iso > tempFile4


# removing original raytracing file.
rm $front
rm $side
rm $top
rm $iso

# changing name of temporary file to that of original file.
mv tempFile1 $front
mv tempFile2 $side
mv tempFile3 $top
mv tempFile4 $iso

# give executable permissions to raytrace file.
chmod 777 $front
chmod 777 $side
chmod 777 $top
chmod 777 $iso

# executing raytrace file. This will produce raw image in .pix tormat and a log
#file.
sh $front
sh $side
sh $top
sh $iso

# converting .pix file to png image using BRLCAD commands.
env /usr/brlcad/dev-7.25.0//bin/pix-png < $front.pix > $front.png
env /usr/brlcad/dev-7.25.0//bin/pix-png < $side.pix > $side.png
env /usr/brlcad/dev-7.25.0//bin/pix-png < $top.pix > $top.png
env /usr/brlcad/dev-7.25.0//bin/pix-png < $iso.pix > $iso.png

chmod 777 $front.png
chmod 777 $side.png
chmod 777 $top.png
chmod 777 $iso.png

# copying final image to public_html for displaying on browser.
cp $front.png ../
cp $side.png ../
cp $top.png ../
cp $iso.png ../
echo "<meta http-equiv=\"refresh\" content=\"1;url=../MultiviewL.html\">"
echo "Processing your Figure:"
echo "<pre>"
