#!/bin/bash


echo Content-type: text/html
echo
echo "<pre>"

# removing old files.
rm -f ff.g
rm -f rt*
rm -f *.pix
rm -f temp*
rm -f ../../cgi-images/*

#initialising variable for the values filled in the form
#length of the top
x=`echo "$QUERY_STRING" | cut -d"&" -f1 | cut -d"=" -f2`
#Breadth of the top
y=`echo "$QUERY_STRING" | cut -d"&" -f2 | cut -d"=" -f2`
#thickness of the top
z=`echo "$QUERY_STRING" | cut -d"&" -f3 | cut -d"=" -f2`
#length of leg
x1=`echo "$QUERY_STRING" | cut -d"&" -f4 | cut -d"=" -f2`
#width of leg
y1=`echo "$QUERY_STRING" | cut -d"&" -f5 | cut -d"=" -f2`
z1=`expr $x + 1`
x2=`expr $x1 - 1`
y2=`expr $y1 / 2`
#defining various views
front=frontview
side=sideview
top=topview
iso=isoview

cat <<EOF | env /usr/brlcad/dev-7.25.0/bin//mged -c try.g
in s rcc 0 0 0 0 $z 0 $x
in s1 rpp -$z1 -$x 0 $x1 0 $y1
in s2 rpp $x $z1 0 $x1 0 $y1
in s3 rcc -$z1 $x2 $y2 1 0 0 $y2
in s4 rcc $xmax -$x2 $y2 1 0 0 $y2
in s5 rcc 0 0 0 0 $z 0 $y
r reg u s u s1 u s2 
r reg1 u reg - s3 - s4 - s5 
mater reg1 plastic 255 0 0 0
B reg1 
ae 0 0
saveview $front
ae 270 0
saveview $side
ae -90 90 
saveview $top
ae 30 30
saveview $iso
EOF

# adding "env /usr/brlcad/bin/" in the beginning of 2nd line of raytracing file
# and sending output to temporary file.
sed '2cenv /usr/brlcad/dev-7.25.0//bin/rt -M \\' $front > tempFile1
sed '2cenv /usr/brlcad/dev-7.25.0//bin/rt -M \\' $side > tempFile2
sed '2cenv /usr/brlcad/dev-7.25.0//bin/rt -M \\' $top > tempFile3
sed '2cenv /usr/brlcad/dev-7.25.0//bin/rt -M \\' $iso > tempFile4


# removing original raytracing file.
rm $front
rm $side
rm $top
rm $iso

# changing name of temporary file to that of original file.
mv tempFile1 $front
mv tempFile2 $side
mv tempFile3 $top
mv tempFile4 $iso

# give executable permissions to raytrace file.
chmod 777 $front
chmod 777 $side
chmod 777 $top
chmod 777 $iso

# executing raytrace file. This will produce raw image in .pix tormat and a log
#file.
sh $front
sh $side
sh $top
sh $iso

# converting .pix file to png image using BRLCAD commands.
env /usr/brlcad/dev-7.25.0//bin/pix-png < $front.pix > $front.png
env /usr/brlcad/dev-7.25.0//bin/pix-png < $side.pix > $side.png
env /usr/brlcad/dev-7.25.0//bin/pix-png < $top.pix > $top.png
env /usr/brlcad/dev-7.25.0//bin/pix-png < $iso.pix > $iso.png

chmod 777 $front.png
chmod 777 $side.png
chmod 777 $top.png
chmod 777 $iso.png

# copying final image to public_html for displaying on browser.
cp $front.png ../
cp $side.png ../
cp $top.png ../
cp $iso.png ../
echo "<meta http-equiv=\"refresh\" content=\"1;url=../try1.html\">"
echo "Processing your Figure:"
echo "<pre>"
 
